export const parasiteTypes = [
  { id: 'fleas', label: { zh: '跳蚤', en: 'Fleas' } },
  { id: 'ticks', label: { zh: '蜱虫', en: 'Ticks' } },
  { id: 'heartworm', label: { zh: '心丝虫', en: 'Heartworm' } },
  { id: 'roundworm', label: { zh: '蛔虫', en: 'Roundworms' } },
  { id: 'hookworm', label: { zh: '钩虫', en: 'Hookworms' } },
  { id: 'tapeworm', label: { zh: '绦虫', en: 'Tapeworms' } },
  { id: 'whipworm', label: { zh: '鞭虫', en: 'Whipworms' } },
  { id: 'mites', label: { zh: '螨虫/疥螨', en: 'Mites / mange' } },
  { id: 'earMites', label: { zh: '耳螨', en: 'Ear mites' } },
];

export const parasiteProfiles = [
  {
    id: 'external',
    icon: 'EX',
    name: { zh: '外寄生虫：跳蚤、蜱虫、螨虫', en: 'External parasites: fleas, ticks, mites' },
    transmission: {
      zh: '草地、犬只接触、环境虫卵和幼虫，蜱虫常来自灌木和高草区域。',
      en: 'Exposure from grass, other dogs, indoor immature flea stages, and tick habitat such as brush or tall grass.',
    },
    symptoms: {
      zh: '瘙痒、掉毛、皮屑、红疹、耳道分泌物，蜱叮咬后可见皮肤附着虫体。',
      en: 'Itching, hair loss, scale, redness, ear discharge, or attached ticks on the skin.',
    },
    risk: {
      zh: '跳蚤可导致过敏性皮炎并传播绦虫；蜱虫可传播多种病原；螨虫可造成严重皮肤病。',
      en: 'Fleas may trigger allergy dermatitis and transmit tapeworms; ticks can transmit pathogens; mites can cause significant skin disease.',
    },
    prevention: {
      zh: '全年或高风险季节持续预防，结合环境清洁、外出后检查皮肤和耳道。',
      en: 'Use year-round or seasonal prevention based on risk, plus environmental cleaning and post-walk skin and ear checks.',
    },
    vet: {
      zh: '出现持续瘙痒、耳道疼痛、蜱虫叮咬后发热或精神沉郁时应就医。',
      en: 'Seek veterinary care for persistent itching, painful ears, fever or lethargy after tick exposure.',
    },
  },
  {
    id: 'intestinal',
    icon: 'GI',
    name: { zh: '肠道寄生虫：蛔虫、钩虫、绦虫、鞭虫', en: 'Intestinal worms: roundworms, hookworms, tapeworms, whipworms' },
    transmission: {
      zh: '摄入虫卵、污染土壤或粪便、捕食中间宿主；幼犬可经母体或乳汁感染部分虫种。',
      en: 'Ingestion of eggs, contaminated soil or feces, prey or intermediate hosts; puppies can acquire some worms from the dam or milk.',
    },
    symptoms: {
      zh: '腹泻、呕吐、便血、消瘦、腹围增大，绦虫节片可能在肛周或粪便中可见。',
      en: 'Diarrhea, vomiting, bloody stool, weight loss, pot belly, or visible tapeworm segments near the anus or in stool.',
    },
    risk: {
      zh: '幼犬、免疫力低下犬风险更高；部分寄生虫具有公共卫生风险。',
      en: 'Puppies and immunocompromised dogs are higher risk; some parasites have zoonotic significance.',
    },
    prevention: {
      zh: '定期粪检、按标签驱虫、及时清理粪便、控制跳蚤和避免捕食。',
      en: 'Routine fecal testing, label-directed deworming, prompt feces removal, flea control, and limiting predation.',
    },
    vet: {
      zh: '幼犬、便血、明显消瘦、反复腹泻或疑似绦虫节片时应做粪检并咨询兽医。',
      en: 'Use fecal testing and veterinary guidance for puppies, bloody stool, weight loss, recurrent diarrhea, or suspected tapeworm segments.',
    },
  },
  {
    id: 'heartworm',
    icon: 'HW',
    name: { zh: '心丝虫', en: 'Heartworm' },
    transmission: {
      zh: '由蚊子传播，犬只被携带感染性幼虫的蚊子叮咬后感染。',
      en: 'Transmitted by mosquitoes carrying infective larvae.',
    },
    symptoms: {
      zh: '早期可能无症状；进展后可咳嗽、运动不耐受、体重下降、呼吸困难。',
      en: 'Early infection may be silent; later signs include cough, exercise intolerance, weight loss, and difficulty breathing.',
    },
    risk: {
      zh: '成虫寄生于心肺血管，可造成严重甚至致命的心肺疾病。',
      en: 'Adult worms inhabit cardiopulmonary vessels and can cause severe or fatal disease.',
    },
    prevention: {
      zh: '按月或按标签持续预防，并按兽医建议进行心丝虫检测。',
      en: 'Use monthly or label-directed prevention and heartworm testing as recommended by a veterinarian.',
    },
    vet: {
      zh: '开始预防前、漏服后或出现呼吸道症状时，应先咨询兽医并检测。',
      en: 'Consult a veterinarian and test before starting prevention, after missed doses, or with respiratory signs.',
    },
  },
];

const S = {
  covers: 'covers',
  partial: 'partial',
  notCovered: 'notCovered',
};

export const productCatalog = [
  {
    id: 'nexgard-spectra-cn',
    name: { zh: '超可信 NexGard Spectra', en: 'NexGard Spectra China' },
    region: { zh: '中国/双语', en: 'China / bilingual' },
    sourceUrl:
      'https://www.boehringer-ingelheim.cn/animal-health/chanpin/ultra-trust-chewable-afranalmilbemycin-oxime-tablets',
    activeIngredients: { zh: '阿福拉纳、米尔贝肟', en: 'Afoxolaner, milbemycin oxime' },
    mechanism: {
      zh: '异噁唑啉类干扰节肢动物氯离子通道；大环内酯类影响线虫神经肌肉传导。',
      en: 'Isoxazoline activity disrupts arthropod chloride channels; macrocyclic lactone activity affects nematode neuromuscular transmission.',
    },
    form: { zh: '口服咀嚼片', en: 'Oral chewable tablet' },
    useRange: { zh: '按当地标签和体重规格使用', en: 'Use by local label and weight band' },
    prescription: { zh: '按当地法规和兽医建议', en: 'Follow local regulations and veterinary advice' },
    notes: { zh: '覆盖较广，但绦虫通常需要其他成分。', en: 'Broad spectrum, but tapeworms usually require another active ingredient.' },
    spectrum: {
      fleas: S.covers,
      ticks: S.covers,
      heartworm: S.covers,
      roundworm: S.covers,
      hookworm: S.covers,
      tapeworm: S.notCovered,
      whipworm: S.partial,
      mites: S.partial,
      earMites: S.partial,
    },
  },
  {
    id: 'nexgard-plus-us',
    name: { zh: 'NexGard PLUS', en: 'NexGard PLUS' },
    region: { zh: '国际/美国', en: 'International / US' },
    sourceUrl:
      'https://animalhealth.boehringer-ingelheim.com/pets/canine/products/parasiticides/nexgard-plus/',
    activeIngredients: { zh: '阿福拉纳、莫昔克丁、噻嘧啶', en: 'Afoxolaner, moxidectin, pyrantel' },
    mechanism: {
      zh: '异噁唑啉杀灭跳蚤蜱虫；大环内酯和噻嘧啶作用于线虫。',
      en: 'Isoxazoline activity targets fleas and ticks; moxidectin and pyrantel target nematodes.',
    },
    form: { zh: '口服咀嚼片', en: 'Oral chewable tablet' },
    useRange: { zh: '按美国标签和体重规格使用', en: 'Use by US label and weight band' },
    prescription: { zh: '美国为处方药', en: 'Prescription product in the US' },
    notes: { zh: '预防心丝虫前需按兽医建议检测。', en: 'Heartworm testing should follow veterinary guidance before prevention.' },
    spectrum: {
      fleas: S.covers,
      ticks: S.covers,
      heartworm: S.covers,
      roundworm: S.covers,
      hookworm: S.covers,
      tapeworm: S.notCovered,
      whipworm: S.notCovered,
      mites: S.notCovered,
      earMites: S.notCovered,
    },
  },
  {
    id: 'simparica-trio-us',
    name: { zh: 'Simparica Trio', en: 'Simparica Trio' },
    region: { zh: '国际/美国', en: 'International / US' },
    sourceUrl:
      'https://dailymed.nlm.nih.gov/dailymed/fda/fdaDrugXsl.cfm?setid=0f83bcf4-7e89-479f-a980-4cb40456ee78',
    activeIngredients: { zh: '沙罗拉纳、莫昔克丁、噻嘧啶', en: 'Sarolaner, moxidectin, pyrantel' },
    mechanism: {
      zh: '异噁唑啉针对跳蚤蜱虫；莫昔克丁和噻嘧啶针对心丝虫幼虫及部分肠道线虫。',
      en: 'Sarolaner targets fleas and ticks; moxidectin and pyrantel cover heartworm larvae and selected intestinal nematodes.',
    },
    form: { zh: '口服咀嚼片', en: 'Oral chewable tablet' },
    useRange: { zh: '按 FDA 标签、年龄和体重限制使用', en: 'Use by FDA label age and weight restrictions' },
    prescription: { zh: '美国为处方药', en: 'Prescription product in the US' },
    notes: { zh: '不用于治疗已存在的心丝虫成虫感染。', en: 'Not for treatment of existing adult heartworm infection.' },
    spectrum: {
      fleas: S.covers,
      ticks: S.covers,
      heartworm: S.covers,
      roundworm: S.covers,
      hookworm: S.covers,
      tapeworm: S.notCovered,
      whipworm: S.notCovered,
      mites: S.partial,
      earMites: S.notCovered,
    },
  },
  {
    id: 'bravecto-us',
    name: { zh: 'Bravecto', en: 'Bravecto' },
    region: { zh: '国际', en: 'International' },
    sourceUrl: 'https://us.bravecto.com/fleas-ticks/',
    activeIngredients: { zh: '氟雷拉纳', en: 'Fluralaner' },
    mechanism: {
      zh: '异噁唑啉类，作用于节肢动物神经系统氯离子通道。',
      en: 'Isoxazoline activity on arthropod nervous system chloride channels.',
    },
    form: { zh: '口服咀嚼片或外用滴剂，依产品而定', en: 'Oral chew or topical product depending on presentation' },
    useRange: { zh: '按标签年龄、体重和剂型使用', en: 'Use by label age, weight, and formulation' },
    prescription: { zh: '部分地区为处方药', en: 'Prescription status varies by market' },
    notes: { zh: '主要用于跳蚤和蜱虫；不覆盖心丝虫或肠道蠕虫。', en: 'Primarily flea and tick coverage; does not cover heartworm or intestinal worms.' },
    spectrum: {
      fleas: S.covers,
      ticks: S.covers,
      heartworm: S.notCovered,
      roundworm: S.notCovered,
      hookworm: S.notCovered,
      tapeworm: S.notCovered,
      whipworm: S.notCovered,
      mites: S.partial,
      earMites: S.notCovered,
    },
  },
  {
    id: 'heartgard-plus-cn',
    name: { zh: '犬心保 Heartgard Plus', en: 'Heartgard Plus China' },
    region: { zh: '中国/双语', en: 'China / bilingual' },
    sourceUrl:
      'https://www.boehringer-ingelheim.cn/animal-health/chanpin/canine-cardioprotection-chewable-ivermectin-dihydroxynaphthylate-thiamphenicol',
    activeIngredients: { zh: '伊维菌素、双羟萘酸噻嘧啶', en: 'Ivermectin, pyrantel pamoate' },
    mechanism: {
      zh: '大环内酯类和噻嘧啶作用于线虫神经肌肉系统。',
      en: 'Macrocyclic lactone and pyrantel activity on nematode neuromuscular systems.',
    },
    form: { zh: '口服咀嚼片', en: 'Oral chewable tablet' },
    useRange: { zh: '按当地标签和体重规格使用', en: 'Use by local label and weight band' },
    prescription: { zh: '按当地法规和兽医建议', en: 'Follow local regulations and veterinary advice' },
    notes: { zh: '用于心丝虫预防及部分肠道线虫，不覆盖跳蚤蜱虫。', en: 'For heartworm prevention and selected intestinal nematodes; no flea or tick coverage.' },
    spectrum: {
      fleas: S.notCovered,
      ticks: S.notCovered,
      heartworm: S.covers,
      roundworm: S.covers,
      hookworm: S.covers,
      tapeworm: S.notCovered,
      whipworm: S.notCovered,
      mites: S.notCovered,
      earMites: S.notCovered,
    },
  },
  {
    id: 'heartgard-plus-us',
    name: { zh: 'Heartgard Plus', en: 'Heartgard Plus' },
    region: { zh: '国际/美国', en: 'International / US' },
    sourceUrl:
      'https://animalhealth.boehringer-ingelheim.com/pets/canine/products/parasiticides/heartgard-plus',
    activeIngredients: { zh: '伊维菌素、噻嘧啶', en: 'Ivermectin, pyrantel' },
    mechanism: {
      zh: '伊维菌素预防心丝虫幼虫发育，噻嘧啶针对蛔虫和钩虫。',
      en: 'Ivermectin prevents heartworm larval development; pyrantel targets roundworms and hookworms.',
    },
    form: { zh: '口服咀嚼片', en: 'Oral chewable tablet' },
    useRange: { zh: '按美国标签和体重规格使用', en: 'Use by US label and weight band' },
    prescription: { zh: '美国为处方药', en: 'Prescription product in the US' },
    notes: { zh: '不覆盖跳蚤、蜱虫、绦虫或鞭虫。', en: 'No flea, tick, tapeworm, or whipworm coverage.' },
    spectrum: {
      fleas: S.notCovered,
      ticks: S.notCovered,
      heartworm: S.covers,
      roundworm: S.covers,
      hookworm: S.covers,
      tapeworm: S.notCovered,
      whipworm: S.notCovered,
      mites: S.notCovered,
      earMites: S.notCovered,
    },
  },
  {
    id: 'interceptor-plus-us',
    name: { zh: 'Interceptor Plus', en: 'Interceptor Plus' },
    region: { zh: '国际/美国', en: 'International / US' },
    sourceUrl: 'https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=86b367e3-64e5-4c44-9961-6caea5d12e75',
    activeIngredients: { zh: '米尔贝肟、吡喹酮', en: 'Milbemycin oxime, praziquantel' },
    mechanism: {
      zh: '米尔贝肟针对心丝虫幼虫及线虫；吡喹酮破坏绦虫体表和钙离子稳态。',
      en: 'Milbemycin targets heartworm larvae and nematodes; praziquantel disrupts cestode tegument and calcium balance.',
    },
    form: { zh: '口服咀嚼片', en: 'Oral chewable tablet' },
    useRange: { zh: '按美国标签、年龄和体重限制使用', en: 'Use by US label age and weight restrictions' },
    prescription: { zh: '美国为处方药', en: 'Prescription product in the US' },
    notes: { zh: '覆盖多种肠道蠕虫和心丝虫预防，但不覆盖跳蚤蜱虫。', en: 'Covers several intestinal worms and heartworm prevention, but not fleas or ticks.' },
    spectrum: {
      fleas: S.notCovered,
      ticks: S.notCovered,
      heartworm: S.covers,
      roundworm: S.covers,
      hookworm: S.covers,
      tapeworm: S.covers,
      whipworm: S.covers,
      mites: S.notCovered,
      earMites: S.notCovered,
    },
  },
  {
    id: 'drontal-plus-cn',
    name: { zh: '拜宠清 Drontal Plus', en: 'Drontal Plus China' },
    region: { zh: '中国/双语', en: 'China / bilingual' },
    sourceUrl: 'https://yourpetandyou.elanco.com/us/our-products/drontal-plus-for-dogs',
    activeIngredients: { zh: '吡喹酮、噻嘧啶、非班太尔', en: 'Praziquantel, pyrantel, febantel' },
    mechanism: {
      zh: '吡喹酮针对绦虫；噻嘧啶和非班太尔针对多种肠道线虫。',
      en: 'Praziquantel targets tapeworms; pyrantel and febantel target multiple intestinal nematodes.',
    },
    form: { zh: '口服片剂', en: 'Oral tablet' },
    useRange: { zh: '按当地标签和体重规格使用', en: 'Use by local label and weight band' },
    prescription: { zh: '按当地法规和兽医建议', en: 'Follow local regulations and veterinary advice' },
    notes: { zh: '肠道蠕虫药，不覆盖跳蚤蜱虫或心丝虫预防。', en: 'Intestinal wormer; no flea, tick, or heartworm prevention coverage.' },
    spectrum: {
      fleas: S.notCovered,
      ticks: S.notCovered,
      heartworm: S.notCovered,
      roundworm: S.covers,
      hookworm: S.covers,
      tapeworm: S.covers,
      whipworm: S.covers,
      mites: S.notCovered,
      earMites: S.notCovered,
    },
  },
  {
    id: 'drontal-plus-us',
    name: { zh: 'Drontal Plus', en: 'Drontal Plus' },
    region: { zh: '国际/美国', en: 'International / US' },
    sourceUrl: 'https://yourpetandyou.elanco.com/us/our-products/drontal-plus-for-dogs',
    activeIngredients: { zh: '吡喹酮、噻嘧啶、非班太尔', en: 'Praziquantel, pyrantel pamoate, febantel' },
    mechanism: {
      zh: '吡喹酮针对绦虫；噻嘧啶和非班太尔针对蛔虫、钩虫、鞭虫等肠道线虫。',
      en: 'Praziquantel targets tapeworms; pyrantel pamoate and febantel target intestinal nematodes including roundworms, hookworms, and whipworms.',
    },
    form: { zh: '口服片剂', en: 'Oral tablet' },
    useRange: { zh: '按美国标签和体重规格使用', en: 'Use by US label and weight band' },
    prescription: { zh: '美国为处方药', en: 'Prescription product in the US' },
    notes: { zh: '肠道蠕虫药，不覆盖跳蚤蜱虫或心丝虫预防。', en: 'Intestinal wormer; no flea, tick, or heartworm prevention coverage.' },
    spectrum: {
      fleas: S.notCovered,
      ticks: S.notCovered,
      heartworm: S.notCovered,
      roundworm: S.covers,
      hookworm: S.covers,
      tapeworm: S.covers,
      whipworm: S.covers,
      mites: S.notCovered,
      earMites: S.notCovered,
    },
  },
  {
    id: 'revolution-cn',
    name: { zh: '大宠爱 Revolution / Selamectin', en: 'Revolution / Selamectin China' },
    region: { zh: '中国/双语', en: 'China / bilingual' },
    sourceUrl: 'https://www.zoetispetcare.com/products/revolution',
    activeIngredients: { zh: '塞拉菌素', en: 'Selamectin' },
    mechanism: {
      zh: '大环内酯类，影响寄生虫谷氨酸门控氯离子通道。',
      en: 'Macrocyclic lactone activity affecting parasite glutamate-gated chloride channels.',
    },
    form: { zh: '外用滴剂', en: 'Topical solution' },
    useRange: { zh: '按当地标签、犬龄和体重使用', en: 'Use by local label, age, and weight' },
    prescription: { zh: '按当地法规和兽医建议', en: 'Follow local regulations and veterinary advice' },
    notes: { zh: '常用于跳蚤、耳螨、疥螨及心丝虫预防；蜱虫覆盖依地区标签不同。', en: 'Often used for fleas, ear mites, sarcoptic mange, and heartworm prevention; tick coverage varies by market label.' },
    spectrum: {
      fleas: S.covers,
      ticks: S.partial,
      heartworm: S.covers,
      roundworm: S.partial,
      hookworm: S.partial,
      tapeworm: S.notCovered,
      whipworm: S.notCovered,
      mites: S.covers,
      earMites: S.covers,
    },
  },
  {
    id: 'revolution-us',
    name: { zh: 'Revolution', en: 'Revolution' },
    region: { zh: '国际/美国', en: 'International / US' },
    sourceUrl: 'https://www.zoetispetcare.com/products/revolution',
    activeIngredients: { zh: '塞拉菌素', en: 'Selamectin' },
    mechanism: {
      zh: '大环内酯类，影响寄生虫谷氨酸门控氯离子通道，用于部分外寄生虫和心丝虫预防。',
      en: 'Macrocyclic lactone activity affecting parasite glutamate-gated chloride channels for selected external parasites and heartworm prevention.',
    },
    form: { zh: '外用滴剂', en: 'Topical solution' },
    useRange: { zh: '按美国标签、犬龄和体重使用', en: 'Use by US label, age, and weight' },
    prescription: { zh: '美国为处方药', en: 'Prescription product in the US' },
    notes: { zh: '犬用标签通常覆盖跳蚤、耳螨、疥螨和心丝虫预防；蜱虫覆盖应以当地标签为准。', en: 'Dog labeling commonly covers fleas, ear mites, sarcoptic mange, and heartworm prevention; tick claims should be checked against the local label.' },
    spectrum: {
      fleas: S.covers,
      ticks: S.partial,
      heartworm: S.covers,
      roundworm: S.notCovered,
      hookworm: S.notCovered,
      tapeworm: S.notCovered,
      whipworm: S.notCovered,
      mites: S.covers,
      earMites: S.covers,
    },
  },
  {
    id: 'frontline-plus-cn',
    name: { zh: '福来恩 Frontline Plus', en: 'Frontline Plus China' },
    region: { zh: '中国/双语', en: 'China / bilingual' },
    sourceUrl: 'https://frontline.com/',
    activeIngredients: { zh: '非泼罗尼、S-烯虫酯', en: 'Fipronil, (S)-methoprene' },
    mechanism: {
      zh: '非泼罗尼作用于节肢动物 GABA 氯离子通道；S-烯虫酯为昆虫生长调节剂。',
      en: 'Fipronil acts on arthropod GABA chloride channels; (S)-methoprene is an insect growth regulator.',
    },
    form: { zh: '外用滴剂', en: 'Topical solution' },
    useRange: { zh: '按当地标签和体重规格使用', en: 'Use by local label and weight band' },
    prescription: { zh: '按当地法规和兽医建议', en: 'Follow local regulations and veterinary advice' },
    notes: { zh: '主要用于跳蚤和蜱虫，不覆盖心丝虫或肠道蠕虫。', en: 'Primarily fleas and ticks; no heartworm or intestinal worm coverage.' },
    spectrum: {
      fleas: S.covers,
      ticks: S.covers,
      heartworm: S.notCovered,
      roundworm: S.notCovered,
      hookworm: S.notCovered,
      tapeworm: S.notCovered,
      whipworm: S.notCovered,
      mites: S.partial,
      earMites: S.notCovered,
    },
  },
  {
    id: 'frontline-plus-us',
    name: { zh: 'Frontline Plus', en: 'Frontline Plus' },
    region: { zh: '国际/美国', en: 'International / US' },
    sourceUrl: 'https://frontline.com/',
    activeIngredients: { zh: '非泼罗尼、S-烯虫酯', en: 'Fipronil, (S)-methoprene' },
    mechanism: {
      zh: '非泼罗尼作用于节肢动物 GABA 氯离子通道；S-烯虫酯阻断跳蚤卵和幼虫发育。',
      en: 'Fipronil acts on arthropod GABA chloride channels; (S)-methoprene prevents flea egg and larval development.',
    },
    form: { zh: '外用滴剂', en: 'Topical solution' },
    useRange: { zh: '按美国标签和体重规格使用', en: 'Use by US label and weight band' },
    prescription: { zh: '美国通常为非处方，仍应按标签使用', en: 'Usually non-prescription in the US, but use by label' },
    notes: { zh: '主要用于跳蚤和蜱虫，不覆盖心丝虫或肠道蠕虫。', en: 'Primarily fleas and ticks; no heartworm or intestinal worm coverage.' },
    spectrum: {
      fleas: S.covers,
      ticks: S.covers,
      heartworm: S.notCovered,
      roundworm: S.notCovered,
      hookworm: S.notCovered,
      tapeworm: S.notCovered,
      whipworm: S.notCovered,
      mites: S.partial,
      earMites: S.notCovered,
    },
  },
];

export const ingredients = [
  {
    name: { zh: '阿福拉纳 / 沙罗拉纳 / 氟雷拉纳', en: 'Afoxolaner / Sarolaner / Fluralaner' },
    className: { zh: '异噁唑啉类', en: 'Isoxazolines' },
    mechanism: {
      zh: '主要作用于跳蚤和蜱虫神经系统氯离子通道，使其过度兴奋后死亡。犬只如有癫痫或神经系统病史，应先咨询兽医。',
      en: 'Target chloride channels in flea and tick nervous systems, causing hyperexcitation and death. Dogs with seizure or neurologic history need veterinary guidance.',
    },
  },
  {
    name: { zh: '伊维菌素 / 米尔贝肟 / 莫昔克丁 / 塞拉菌素', en: 'Ivermectin / Milbemycin / Moxidectin / Selamectin' },
    className: { zh: '大环内酯类', en: 'Macrocyclic lactones' },
    mechanism: {
      zh: '影响线虫和部分节肢动物的氯离子通道，常用于心丝虫预防及部分线虫或螨虫控制。',
      en: 'Affect chloride channels in nematodes and some arthropods; commonly used for heartworm prevention and selected nematode or mite control.',
    },
  },
  {
    name: { zh: '吡喹酮', en: 'Praziquantel' },
    className: { zh: '抗绦虫药', en: 'Cestocide' },
    mechanism: {
      zh: '破坏绦虫体表并改变钙离子通透性，使绦虫麻痹、脱落并被消化。',
      en: 'Disrupts tapeworm tegument and calcium handling, leading to paralysis, detachment, and digestion.',
    },
  },
  {
    name: { zh: '噻嘧啶 / 非班太尔', en: 'Pyrantel / Febantel' },
    className: { zh: '肠道线虫药', en: 'Intestinal nematode agents' },
    mechanism: {
      zh: '噻嘧啶使线虫痉挛性麻痹；非班太尔经代谢后干扰虫体能量代谢和微管功能。',
      en: 'Pyrantel causes spastic paralysis in nematodes; febantel metabolites interfere with parasite energy metabolism and microtubule function.',
    },
  },
  {
    name: { zh: '非泼罗尼 / S-烯虫酯', en: 'Fipronil / (S)-methoprene' },
    className: { zh: '外用杀虫剂与昆虫生长调节剂', en: 'Topical insecticide and insect growth regulator' },
    mechanism: {
      zh: '非泼罗尼杀灭成虫跳蚤蜱虫；S-烯虫酯阻断跳蚤卵和幼虫发育。',
      en: 'Fipronil kills adult fleas and ticks; (S)-methoprene prevents flea egg and larval development.',
    },
  },
];

export const safetyNotes = [
  {
    title: { zh: '心丝虫预防前先确认风险', en: 'Confirm heartworm risk before prevention' },
    body: {
      zh: '心丝虫预防药通常不用于治疗成虫感染。开始、恢复或漏服后如何检测，应按兽医建议执行。',
      en: 'Heartworm preventives are generally not adulticide treatments. Testing before starting, restarting, or after missed doses should follow veterinary advice.',
    },
  },
  {
    title: { zh: '处方和标签因地区不同', en: 'Prescription and labels vary by market' },
    body: {
      zh: '同一品牌在中国、美国或其他地区的批准适应症、年龄体重限制和处方状态可能不同，查询时以当地标签为准。',
      en: 'The same brand may have different indications, age or weight restrictions, and prescription status in China, the US, or other markets. Use the local label.',
    },
  },
  {
    title: { zh: '异噁唑啉类需关注神经系统史', en: 'Isoxazolines require neurologic history awareness' },
    body: {
      zh: '阿福拉纳、沙罗拉纳、氟雷拉纳等成分通常用于跳蚤蜱虫，但有癫痫或神经系统异常史的犬只应先咨询兽医。',
      en: 'Afoxolaner, sarolaner, fluralaner, and related actives are common flea and tick agents, but dogs with seizure or neurologic history should be discussed with a veterinarian.',
    },
  },
  {
    title: { zh: '不要用犬猫药互换', en: 'Do not interchange dog and cat products' },
    body: {
      zh: '犬用和猫用产品浓度、辅料和禁忌可能不同。尤其外用药不可自行跨物种使用。',
      en: 'Dog and cat products can differ in concentration, excipients, and contraindications. Do not swap topical products across species without veterinary direction.',
    },
  },
];

export const sourceLinks = [
  { name: { zh: 'CAPC 犬寄生虫防控', en: 'CAPC canine parasite guidance' }, url: 'https://capcvet.org/guidelines/' },
  { name: { zh: 'ESCCAP 指南', en: 'ESCCAP guidelines' }, url: 'https://www.esccap.org/guidelines/' },
  { name: { zh: '勃林格殷格翰中国：超可信', en: 'Boehringer Ingelheim China: NexGard Spectra' }, url: 'https://www.boehringer-ingelheim.cn/animal-health/chanpin/ultra-trust-chewable-afranalmilbemycin-oxime-tablets' },
  { name: { zh: '勃林格殷格翰：NexGard PLUS', en: 'Boehringer Ingelheim: NexGard PLUS' }, url: 'https://animalhealth.boehringer-ingelheim.com/pets/canine/products/parasiticides/nexgard-plus/' },
  { name: { zh: 'DailyMed：Simparica Trio', en: 'DailyMed: Simparica Trio' }, url: 'https://dailymed.nlm.nih.gov/dailymed/fda/fdaDrugXsl.cfm?setid=0f83bcf4-7e89-479f-a980-4cb40456ee78' },
  { name: { zh: 'DailyMed：Interceptor Plus', en: 'DailyMed: Interceptor Plus' }, url: 'https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=86b367e3-64e5-4c44-9961-6caea5d12e75' },
  { name: { zh: 'Elanco：Drontal Plus', en: 'Elanco: Drontal Plus' }, url: 'https://yourpetandyou.elanco.com/us/our-products/drontal-plus-for-dogs' },
  { name: { zh: 'Zoetis：Revolution', en: 'Zoetis: Revolution' }, url: 'https://www.zoetispetcare.com/products/revolution' },
  { name: { zh: 'Bravecto 官方站', en: 'Bravecto official site' }, url: 'https://us.bravecto.com/fleas-ticks/' },
];
